name: Server Deploy
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ main ]
 
  workflow_dispatch:
 
jobs:
  deploy-via-ssh:
    name: deploy (oci)
    runs-on: ubuntu-latest
    steps:
    - name: ⚙️ Deploy on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ionos-s2.val005.fr
        username: bots
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
         cd /var/bots/fast_theo_bot_discord/
         pm2 stop bot.js
         git pull
         npm i
         pm2 start bot.js
